language: node_js
node_js:
- 6
cache:
  directories:
  - node_modules
script:
- npm run build
- npm test
deploy:
  provider: firebase
  token:
    secure: "H5ifKBfCdQcmTAYMH4ZBV5LvcYy+KLw8EKgS7ltwI6X6bsk6Zvhz8GzQPS2p6rU3FTi/FiA+uLt2t+0MK9U4nG8HZrKrwuHvwRX20RYWhLAaGCHF2tLhX2G5XxvrGvG2hsOS7FDKv+IP3xkJl++YirXOoxfC19vzkG1dGC0gIQ5zqke2lgRyZwRC+nLGc3ax1+W1jKZS7yLLWsSGwO+DyBaz/w5LvyDWYFTL81oMvWSKe3/g7uwHheJCQ9V8pmA/FsCuVbb1BDWENSgtwOxb8SvTl0MwCcmJE9RfxHnnqv9SUH2REFKEhKG91/EYAUellwuaNPg9iRqvkQBDUzCdsYK4SWfCxU4k0NTSV+F1mBAT14UoOMyR7JkdG9eI3IFWvVmfZ40GRRCEBo7Id/nNtHjrrd0QYM/GJph74HgPb/m+3cvEpZmtpd64y4J4GoExpanBT9Hpw9LjTxOsdgHmDDPL1V+t+VN4SxnzjktIg7u5y6ERx9zWtcrz3It7M0uElaqh0CTFGBaR9a4Pb53fOA8Oan3+TRF5kLOFxZ2na3Ws9EBXwYjU+inY5utK33MJtgF+vy0nUBk5E7iv3y38rQ+YQrdgs4arCLp4vkOVE41wkN8vicBgx2pvWEJM0rToTYOO1Z8GAea/j3AriCQ4zAgDnwCqQYXv4ezA2MPtobQ="
  project: "todo-mischief"